version: "3.7"

services:
  database:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=prisma-demo
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password